version: '3.7'
services:
  accounts:
    build: ./expenses-app
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
