version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:1567'

  accounts:
    build: .
    depends_on:
     - rabbitmq
    ports:
      - '8080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
